### ISSUE TITLE
[EFB] Weight and Balance Bulk Cargo CG change

### ISSUE THREAD

**Issue by MachJok** [MachJok/747-Data#14]
Issue: Adding weight in Bulk Cargo has less effect to MAC CG than Cargo 3.
Expected Behavior: Bulk Cargo should affect MAC CG more than Cargo 3 because Bulk Cargo is aft of Cargo 3.
10,000lbs in Bulk Cargo
![Screenshot from 2021-07-16 09-08-16](https://user-images.githubusercontent.com/63207487/125977290-fb6e4062-8982-48ac-94f1-4f14d5fa526c.png)

10,000lbs in Cargo 3
![Screenshot from 2021-07-16 09-08-28](https://user-images.githubusercontent.com/63207487/125977543-c60c8408-5d48-45e1-a80a-72c10b744eaf.png)

**Comment by FelisLeopard** [comment]
Fixing it in 0.9.14
