### ISSUE TITLE
Hole in the cockpits  ceiling cladding next to the circuit breakers

### ISSUE THREAD

**Issue by Willi614** [MachJok/747-Data#15]
![B742_PW_Felis - 2021-07-17 14 34 55](https://user-images.githubusercontent.com/87571118/126037292-793ceab3-04de-473a-a183-2d8e65f9d865.png)

**Comment by FelisLeopard** [comment]
![image](https://user-images.githubusercontent.com/1625986/126128668-1d924347-d787-4b64-afd6-9453510db9d8.png)
fixed in next patch 0.9.14
