### ISSUE TITLE
Wings bend down too much when fully loaded. Likely caused by changes on the gear springs. 

### ISSUE THREAD

**Issue by Willi614** [MachJok/747-Data#16]
![Schermopname_1065](https://user-images.githubusercontent.com/87571118/126763788-a55c039f-41c8-4741-81e0-8ec8ed6d8b1f.png)

**Comment by FelisLeopard** [comment]
Fixing it right now. Will be in 0.9.15

**Comment by FelisLeopard** [comment]
Fixed in 0.9.15
