### ISSUE TITLE
AP_reset and AT_reset _red and _yellow datarefs both indicate 1 whether the reset button is lit yellow or red within the sim.

### ISSUE THREAD

**Issue by flyingdimebar** [MachJok/747-Data#20]
Presumably if the Captain-side buttons are lit red only B742/front_lamps/AP_reset_red_L and B742/front_lamps/AT_reset_red_L should have values of 1 and B742/front_lamps/AP_reset_yellow_L and B742/front_lamps/AT_reset_yellow_L should have 0 values (vice-versa for red and same applies for _R datarefs for the F/O's side. At least this is the case when the PTT buttons are pressed, in the sim PTT2 lights buttons red, PTT1 lights buttons amber.

**Comment by FelisLeopard** [comment]
There should be another one to set show/hide for red and yellow buttons. I will check it though, so red and yellow wouldn't be 1 both at the same time
