### ISSUE TITLE
Small hole behind FE panel

### ISSUE THREAD

**Issue by iamgrandsonone** [MachJok/747-Data#21]
* 0.9.14
![B742_PW_Felis - 2021-07-25 20 51 37](https://user-images.githubusercontent.com/87272330/126907036-31248052-9eca-497a-8e01-c64666d8a722.png)
![B742_PW_Felis - 2021-07-25 20 51 56](https://user-images.githubusercontent.com/87272330/126907044-b8b97c0b-1ac7-48fe-befe-ef25a1f60186.png)

**Comment by FelisLeopard** [comment]
Fixing it for 0.9.15
