### ISSUE TITLE
Contingency fuel load based on alternate distance not trip distance

### ISSUE THREAD

**Issue by MachJok** [MachJok/747-Data#22]
Current Behavior: In the EFB Load Planner Fuel Calculator with an alternate distance of 0, setting a contingency fuel percentage does not change the fuel load.
with contingency fuel but no alternate distance
![image](https://user-images.githubusercontent.com/63207487/127057959-673d205f-f988-43fd-9689-e8040b015995.png)
no contingency fuel
![image](https://user-images.githubusercontent.com/63207487/127057993-ec7fe9bc-c282-437c-9b69-3c5fc98f46f6.png)

Expected Behavior: Contingency fuel calculations are based on trip fuel (origin to destination) not alternate distance : https://www.eurocockpit.be/sites/default/files/2017-06/Fuel%20policy%20-%20safety%20and%20consistency%2C%20ECA%202017_1.pdf

**Comment by FelisLeopard** [comment]
13608 kg (30000 lb) is the minimum fuel. Apparently with 200 nm cruise, calculated fuel is lower, than this number. Check with longer distances.

**Comment by MachJok** [comment]
Issue resolved in 0.9.15 with all distances
