### ISSUE TITLE
Load manager over loads aircraft

### ISSUE THREAD

**Issue by MachJok** [MachJok/747-Data#23]
Current Behavior: In all load conditions but especially light conditions, using the "Loadsheet Value" option on loading pages results in aircraft weight above loadsheet values
![image](https://user-images.githubusercontent.com/63207487/127058649-b70fa4be-7c5b-44e1-a4b0-4d99edcb2fa0.png)
![image](https://user-images.githubusercontent.com/63207487/127058683-662e5770-24fd-4a7c-8160-0a52fa3132c7.png)
![image](https://user-images.githubusercontent.com/63207487/127058725-096386b7-47d5-4ef7-bab7-c4072fb85f0f.png)
Loadsheet values:
![image](https://user-images.githubusercontent.com/63207487/127058784-351bb738-b8aa-4ef6-b111-0911d8331b8d.png)
SIM values:
![image](https://user-images.githubusercontent.com/63207487/127058810-60714352-0eaa-4b73-b37f-261b427768f8.png)
![image](https://user-images.githubusercontent.com/63207487/127058957-520c69aa-c076-40f5-b411-33e8ed669d7c.png)

**Comment by FelisLeopard** [comment]
Fixed in 0.9.17
