### ISSUE TITLE
Load waypoint function in EFB INS page overrides all waypoints

### ISSUE THREAD

**Issue by MachJok** [MachJok/747-Data#25]
If a flight plan has more than 9 waypoints and is loaded into the EFB, trying to write from waypoint 10 the entire CIVA flight plan is overwritten. 
Suggestion: Flight plan write sequence should follow the Automatic Data Entry Unit (ADEU) flight plan logic 
Page 1: load waypoints 1-9 into CIVA 1-9
Page 2: load waypoints 10-16 into CIVA 1-7
Page 3: load waypoints 17-23 into CIVA 8-5
Page 4 load waypoints 24-30 into CIVA 6-3 etc.

The logic is as follows:
Flying from departure waypoints 1-9 are loaded.
When flying leg 8-9 the next set of waypoints need to be loaded. since 8 and 9 are currently in use, the only available waypoints to write to are 1-7.   then when flying 6-7, the next waypoints can only go to 8->5.

Departure 9 waypoints loaded
1-2-3-4-5-6-7-8-9

Flying Leg 8-9 load waypoints 10-16
8-9--(1-2-3-4-5-6-7)

Flying Leg 6-7 load waypoints 17-23
6-7--(8-9-1-2-3-4-5)

Flying Leg 4-5 load 24-30
4-5--(6-7-8-9-1-2-3)

Flying Leg 2-3 load 31-37
2-3--(4-5-6-7-8-9-1)
etc

**Comment by FelisLeopard** [comment]
Yes. That function is only for rewriting waypoints, using your flightplan and starting from specified waypoint. I made it to cut off initial position and maybe SID, that could be in your flightplan. Usually there is departure airport as a waypoint and you don't want it in your INS plan. This is why default number is 2 there.
