### ISSUE TITLE
Nose wheels rotate when using BetterPushback

### ISSUE THREAD

**Issue by reflectedrealitysimulations** [MachJok/747-Data#3]
When the nose gear is lifted into the tug cradle and the aircraft is pushed or pulled, the nose wheels will rotate as if they are on the ground. The sim should be looking for a dataref “bp/connected” and if it’s set lock the nose wheel rotation.  To be clear, this is the rolling action, not steering. Steering is working as expected.

**Comment by FelisLeopard** [comment]
Fixed it 0.9.13
