### ISSUE TITLE
AP engages into psedo control wheel steeringmode if hardware pitch is outside AP disengagement threshold

### ISSUE THREAD

**Issue by MachJok** [MachJok/747-Data#35]
If the autopilot is turned on when hardware control deflections are outside the disengagement threshold autopilot engages but is unresponsive to flight director commands
![Screenshot from 2021-09-17 08-58-11](https://user-images.githubusercontent.com/63207487/133821666-513d6bec-abe6-408b-8e1b-32b1008cef2c.png)

**Comment by FelisLeopard** [comment]
I increased deadzones for triggering this mode.
