### ISSUE TITLE
CIVA INS DME update longitude field overflow

### ISSUE THREAD

**Issue by MachJok** [MachJok/747-Data#4]
when entering the DME update mode and typing in a longitude, if more numbers are entered than field size, overflow error occurs and each digit has 10 subtracted from it

**Comment by MachJok** [comment]
https://youtu.be/wVIm1eSowHA

**Comment by FelisLeopard** [comment]
It was a problem for all coordinates, when you select negative values. ie. W or S. Fixed in 0.9.13
