### ISSUE TITLE
captain/first officer alternate air source switches and placard

### ISSUE THREAD

**Issue by MachJok** [MachJok/747-Data#8]
Alternate air placard by captain/first officer outboard leg is located off the wall. The switch is not centered in the housing
![Screenshot from 2021-07-09 10-51-21](https://user-images.githubusercontent.com/63207487/125170065-f5fce100-e161-11eb-94de-ad4113536400.png)
![Screenshot from 2021-07-09 10-52-47](https://user-images.githubusercontent.com/63207487/125170078-fdbc8580-e161-11eb-8e54-07e2d93ef942.png)

**Comment by FelisLeopard** [comment]
fixing it for patch 0.9.14

**Comment by FelisLeopard** [comment]
![image](https://user-images.githubusercontent.com/1625986/126140243-6d78d46a-8af3-4f11-b925-cbb2a2994e5f.png)
![image](https://user-images.githubusercontent.com/1625986/126140613-721bdb30-fd35-44b3-9a63-89f662a3b656.png)
