### ISSUE TITLE
Copilot oxygen TEST not working

### ISSUE THREAD

**Issue by iamgrandsonone** [MachJok/747-Data#9]
Copilot oxygen TEST not working, the FLOW did not open:
![unknown](https://user-images.githubusercontent.com/87272330/125200151-b37af780-e27a-11eb-92a1-d55bf9bd8bfc.png)

**Comment by FelisLeopard** [comment]
![image](https://user-images.githubusercontent.com/1625986/126131884-f230bd8d-8b75-4340-b0be-2590569544c5.png)
fixed it for 0.9.14
